name: data-validation
on: push
      branches: [development, data_validation]
    pull_request
      branches: [main, development, data_validation]
jobs:
  validate-data
    runs-on: ubuntu-latest
    